/*Author: Tushar Borole
Discription:It contain url depend on mock or development
Copyright:Seed Inc. 2014*/
(function () {
    'use strict';
App.constant('APP_URL', {
    'development': {
        'loginuser': 'api/login',
        'loggedinuser': 'api/v1/users/loggedInUser',
        'getmail': 'api/v1/mailformat',
        'updatemail': 'api/v1/mailformat',
        'createmail': 'api/v1/mailformat',
        'deletemail': 'api/v1/mailformat',
        'getmailmodule': 'api/v1/mailformat/module',
        'getrole': 'api/v1/roles',
        'invitemail': 'api/v1/users/inviteusers',
        'getuser': 'api/v1/users/search',
        'mailcomponent': 'api/v1/mailformat/components',
        'updatestatus': 'api/v1/users/{{userId}}/status',
        'companydetails': 'api/v1/company/activecompany',
        'updatecompanystatus': 'api/v1/company/{{companyid}}/status',
        'projectdetails': 'api/v1/project/company/{{companyid}}',
        'updateprojectstatus': 'api/v1/project/{{projectid}}/status',
         'teamdetails': 'api/v1/company/{{companyid}}/team/search',
        'updateteamstatus': 'api/v1/project/{{projectid}}/status',
        'getcategory': 'api/v1/category',
        'createcategory': 'api/v1/category',
        'deletecategory': 'api/v1/category/{{categoryid}}',
        'updatecategory': 'api/v1/category/{{categoryid}}',
        'getsubcategory': 'api/v1/category/subcategory',
         'ngodetails': 'api/v1/ngo',
        'updatengostatus': 'api/v1/ngo/{{ngoid}}/status',
        'ngoproject':'api/v1/ngo/{{ngoid}}/ngoproject',
        'ngomember':'api/v1/ngo/{{ngoid}}/ngomember',
        'getcountdashboard':'api/v1/dashboard',
        'getngodashboard':'api/v1/dashboard/ngo?year={{year}}',
        'getcompanydashboard':'api/v1/dashboard/company?year={{year}}',
        'getuserdashboard':'api/v1/dashboard/user?year={{year}}',
        'getuserinvitations':'api/v1/invitation/search',
        'updateinvite':'api/v1/invitation/{{invitationId}}',
        'deleteinvite':'api/v1/invitation/{{invitationId}}',
        'getuserdetails':'api/v1/users/{{userId}}',
        'deleteuser':'api/v1/users/{{userId}}',
        'getregistration':'api/v1/user/manageuser',
        'deleteregistration':'',
        'updateregistration':'',
        'getregistrationdetail':'',
        'resendinvitaion':'',
        'getpaymentinfo':'',
        'resendpaymentinvitaion':'',
        'getstatus':'api/v1/user/manageuser/registrationstatus',
        'getdocument':'',
        'updatedocument':'',
        'createdocument':'',
        'deletedocument':'',
        'updatemailimage':'',
        'updateuser':'api/v1/users/{{userId}}',
        'imageupload':'api/v1/imageupload'

    },
    'mock': {
        'loginuser': 'json/static/login.json',
        'loggedinuser': 'json/static/loggedin.json',
        'getmail': 'json/static/mailjson.json',
        'updatemail': 'json/static/updatemail.json',
        'createmail': 'json/static/createmail.json',
        'deletemail': 'json/static/deletemail.json',
        'getmailmodule': 'json/static/getmailmodule.json',
        'getrole': 'json/static/role.json',
        'invitemail': 'api/v1/users/inviteusers',
        'getuser': 'json/static/user.json',
        'mailcomponent': 'json/static/mailcomponent.json',
        'updatestatus': 'json/static/updatestatus.json',
        'companydetails': 'json/static/company.json',
        'updatecompanystatus': 'api/v1/companystatus.json',
        'projectdetails': 'json/static/project.json',
        'updateprojectstatus': 'json/static/projectstatus.json',
         'teamdetails': 'json/static/team.json',
        'updateteamstatus': 'json/static/teamstatus.json',
         'getcategory': 'json/static/category.json',
        'createcategory': 'json/static/createcategory.json',
        'deletecategory': 'json/static/deletecatgory.json',
        'updatecategory': 'json/static/updatecategory.json',
        'getsubcategory': 'json/static/subcategory.json',
         'ngodetails': 'json/static/ngo.json',
        'updatengostatus': 'json/static/ngostatus.json',
        'ngoproject':'json/static/ngoproject.json',
        'ngomember':'json/static/ngomenber.json',
         'getcountdashboard':'json/static/dashboardcount.json',
        'getngodashboard':'json/static/ngodashboard.json',
        'getcompanydashboard':'json/static/companydashboard.json',
        'getuserdashboard':'json/static/userdashboard.json',
        'getuserinvitations':'json/static/userinvitations.json',
        'updateinvite':'json/static/updateinvitations.json',
        'deleteinvite':'json/static/deleteinvitations.json',
        'getuserdetails':'json/static/userDetails.json',
        'deleteuser':'json/static/userdelete.json',
         'getregistration':'json/static/manageregistration.json',
        'deleteregistration':'',
        'updateregistration':'',
        'getregistrationdetail':'json/static/updateregistration.json',
        'resendinvitaion':'',
          'getpaymentinfo':'',
        'resendpaymentinvitaion':'',
        'getstatus':'json/static/registrationstatus.json',
        'getdocument':'',
        'updatedocument':'',
        'createdocument':'',
        'deletedocument':'',
        'updatemailimage':'',
        'updateuser':'json/static/updateuser.json',
        'imageupload':'imageupload'


    }
});
    }())
